name: Trigger auto deployment for chatbot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/chatbot-AutoDeployTrigger-c9d82bc0-3e2f-4755-96f2-d9c6cbc71d78.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CHATBOT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca62bf0b2f78acr.azurecr.io
          registryUsername: ${{ secrets.CHATBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CHATBOT_REGISTRY_PASSWORD }}
          containerAppName: chatbot
          resourceGroup: kidnixt_rg_0655
          imageToBuild: ca62bf0b2f78acr.azurecr.io/chatbot:${{ github.sha }}
          
            

     

